In [1]:
import sys
import numpy as np
from itertools import product, permutations
from math import sqrt
from tqdm import tqdm
from functools import reduce
from collections import defaultdict

# Problem 1
### 1000보다 작은 자연수 중에서 3 또는 5의 배수를 모두 더하면?
```
10보다 작은 자연수 중에서 3 또는 5의 배수는 3, 5, 6, 9 이고, 이것을 모두 더하면 23입니다.

1000보다 작은 자연수 중에서 3 또는 5의 배수를 모두 더하면 얼마일까요?
```

In [548]:
total = sum([x for x in range(1000) if ((x % 5 == 0) or (x % 3 == 0))])
total

233168

# Problem 2
### 피보나치 수열에서 4백만 이하이면서 짝수인 항의 합
```
피보나치(Fibonacci) 수열의 각 항은 바로 앞의 항 두 개를 더한 것입니다. 1과 2로 시작하는 경우 이 수열은 아래와 같습니다.

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
4백만 이하의 짝수 값을 갖는 모든 피보나치 항을 더하면 얼마가 됩니까?
```

In [33]:
def memoize(func):
    tempMemo = dict()
    def wrapped(n):
        if n in tempMemo:
            return tempMemo[n]
        result = func(n)
        tempMemo[n] = result
        return result
    return wrapped


@memoize
def fib(n):
    if n in (1, 2):
        return 1
    return fib(n-1) + fib(n-2)

In [62]:
%%time
n = 3
r = 3 # 3 번째 항마다 짝수가 나옴

a = 0.

while fib(n) < 4e6:
    a += fib(n)
    n += r
    
print(a)

4613732.0
Wall time: 0 ns


# Problem 3

### 가장 큰 소인수 구하기
```
어떤 수를 소수의 곱으로만 나타내는 것을 소인수분해라 하고, 이 소수들을 그 수의 소인수라고 합니다.
예를 들면 13195의 소인수는 5, 7, 13, 29 입니다.

600851475143의 소인수 중에서 가장 큰 수를 구하세요.
```

In [485]:
def is_prime(n):
    return all([(n%j) for j in range(2, int(n**0.5)+1)]) and n>1

In [147]:
%%time

val = 600851475143

# 함수 수정 필요함.
# 이 문제에 한정된 함수
def find_prime_factors(val):
    n = 2
    prime_factors = []
    while True:
        if is_prime(n):
            if val % n == 0:
                val = val // n
                prime_factors.append(n)
        if val == 1:
            break
        n += 1
    return prime_factors, n

prime_factors, n = find_prime_factors(val)
print(n)

6857
Wall time: 18 ms


In [140]:
prime_factors

[71, 839, 1471, 6857]

In [89]:
71 * 839 * 1471 * 6857 # is same to val

600851475143

# Problem 4

### 세자리 수를 곱해 만들 수 있는 가장 큰 대칭수

```
앞에서부터 읽을 때나 뒤에서부터 읽을 때나 모양이 같은 수를 대칭수(palindrome)라고 부릅니다.

두 자리 수를 곱해 만들 수 있는 대칭수 중 가장 큰 수는 9009 (= 91 × 99) 입니다.

세 자리 수를 곱해 만들 수 있는 가장 큰 대칭수는 얼마입니까?
```

In [131]:
%%time
results = []
for i in range(999, 100, -1):
    for j in range(999, 100, -1):
        val = str(i*j)
        adj = 1 if len(val) == 5 else 0
        if val[:len(val)//2] == val[len(val)//2+adj:][::-1]:
            results.append(int(val))
            break

Wall time: 430 ms


In [134]:
max(results)

906609

# Problem 5
### 1 ~ 20 사이의 어떤 수로도 나누어 떨어지는 가장 작은 수

```
1 ~ 10 사이의 어떤 수로도 나누어 떨어지는 가장 작은 수는 2520입니다.

그러면 1 ~ 20 사이의 어떤 수로도 나누어 떨어지는 가장 작은 수는 얼마입니까?
```

In [1180]:
prime_factorization(232792560, ret=defaultdict(int)) # 크...

defaultdict(int, {2: 4, 3: 2, 5: 1, 7: 1, 11: 1, 13: 1, 17: 1, 19: 1})

In [158]:
# 1~20을 생성할 수만 있으면 ㅇㅋ
# 함수로 짤 수 있을 것 같은데 나중에 시간되면 짜보기
np.prod([2 ** 4, 3 ** 2, 5, 7, 11, 13, 17, 19])

232792560

# Problem 6

### 1부터 100까지 "제곱의 합"과 "합의 제곱"의 차는?

```
1부터 10까지 자연수를 각각 제곱해 더하면 다음과 같습니다 (제곱의 합).

12 + 22 + ... + 102 = 385
1부터 10을 먼저 더한 다음에 그 결과를 제곱하면 다음과 같습니다 (합의 제곱).

(1 + 2 + ... + 10)2 = 552 = 3025
따라서 1부터 10까지 자연수에 대해 "합의 제곱"과 "제곱의 합" 의 차이는 3025 - 385 = 2640 이 됩니다.

그러면 1부터 100까지 자연수에 대해 "합의 제곱"과 "제곱의 합"의 차이는 얼마입니까?
```

In [169]:
np.sum(np.arange(1, 101)) ** 2 - np.sum(np.arange(1, 101) ** 2)

25164150

# Problem 7
### 10001번째의 소수
```
소수를 크기 순으로 나열하면 2, 3, 5, 7, 11, 13, ... 과 같이 됩니다.

이 때 10,001번째의 소수를 구하세요.
```

In [174]:
%%time
prime = 0
count = 0
n = 1
while count < 10001:
    if is_prime(n):
        prime = n
        count += 1
    n += 1

Wall time: 843 ms


# Problem 8
### 1000자리 수 안에서 이어지는 5개 숫자의 곱 중 최댓값은?

In [181]:
s = """
73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450
"""

s = ''.join(s.split('\n'))

In [190]:
%%time
window = 5
results = []
for i in range(len(s)-5):
    results.append(np.prod([int(j) for j in s[i:i+window]]))
max(results)

Wall time: 6.01 ms


40824

# Problem 9

### a + b + c = 1000 이 되는 피타고라스 수

```
세 자연수 a, b, c 가 피타고라스 정리 a^2 + b^2 = c^2 를 만족하면 피타고라스 수라고 부릅니다 (여기서 a < b < c ).
예를 들면 3^2 + 4^2 = 9 + 16 = 25 = 5^2이므로 3, 4, 5는 피타고라스 수입니다.

a + b + c = 1000 인 피타고라스 수 a, b, c는 한 가지 뿐입니다. 이 때, a × b × c 는 얼마입니까?
```

In [392]:
# Unique Solution이 존재
# 이 말인 즉슨 loss=0으로 만드는 global optima가 존재한다는 얘기

# Monte Carlo 및 Deep Learning으로 풀 수 있을지 고려하자!
# 일단은 하드 코딩으로 문제 해결

In [426]:
axis = np.linspace(1, 1000, 1000)
a, b = np.meshgrid(axis, axis)
c = 1000 - a - b
ind = c > 0

a = a[ind]
b = b[ind]
c = c[ind]

In [431]:
a[a ** 2 + b ** 2 == c ** 2]

array([375., 200.])

In [432]:
c[a ** 2 + b ** 2 == c ** 2]

array([425., 425.])

In [433]:
200 ** 2 + 375 ** 2 == 425 ** 2

True

In [434]:
200 * 375 * 425

31875000

# Problem 10
### 이백만 이하 소수의 합
```
10 이하의 소수를 모두 더하면 2 + 3 + 5 + 7 = 17 이 됩니다.

이백만(2,000,000) 이하 소수의 합은 얼마입니까?
```

In [437]:
result = 0
for i in tqdm(range(1, int(2e6)+1)):
    if is_prime(i):
        result += i

100%|█████████████████████████████| 2000000/2000000 [01:22<00:00, 24220.41it/s]


In [438]:
result

142913828922

# Problem 11
### 20×20 격자에서 연속된 네 수의 곱 중 최댓값

In [452]:
s = """
08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
"""

In [466]:
arr = np.array(
    list(
        map(
            lambda x: [int(i) for i in x.split(' ')], 
            s.split('\n')[1:-1]
        )
    )
)

In [546]:
%%time
results = []
for i in range(20-4):
    results.extend(np.prod(arr[:, i:i+4], axis=1)) # horizontal
    results.extend(np.prod(arr.T[:, i:i+4], axis=1)) # vertical
for k in range(-16, 17):
    temp1 = np.diag(arr, k=k)
    temp2 = np.diag(arr[:, ::-1], k=k)
    for i in range(temp1.shape[0]-4+1):
        res1 = np.prod(temp1[i:i+4])
        res2 = np.prod(temp2[i:i+4])
        if isinstance(res1, np.int32):
            res1 = [res1]
        if isinstance(res2, np.int32):
            res2 = [res2]
        results.extend(res1)
        results.extend(res2)
max(results)

Wall time: 2 ms


70600674

# Problem 12
### 500개 이상의 약수를 갖는 가장 작은 삼각수는?

```
1부터 n까지의 자연수를 차례로 더하여 구해진 값을 삼각수라고 합니다.
예를 들어 7번째 삼각수는 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28이 됩니다.
이런 식으로 삼각수를 구해 나가면 다음과 같습니다.

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
이 삼각수들의 약수를 구해 봅시다.

 1: 1
 3: 1, 3
 6: 1, 2, 3, 6
10: 1, 2, 5, 10
15: 1, 3, 5, 15
21: 1, 3, 7, 21
28: 1, 2, 4, 7, 14, 28
위에서 보듯이, 5개 이상의 약수를 갖는 첫번째 삼각수는 28입니다.

그러면 500개 이상의 약수를 갖는 가장 작은 삼각수는 얼마입니까?
```

In [1140]:
# Elliptic Curve Method는 차후 구현
# find_prime_factors 함수를 확장


def prime_factorization(val, n=1, ret=defaultdict(int)):
    while val > n:
        if is_prime(n):
            if val % n == 0:
                val //= n
                ret[n] += 1
                return prime_factorization(val, n, ret)
        n += 1
    ret[n] += 1
    return ret

In [1141]:
prime_factorization(76576500, ret=defaultdict(int))

defaultdict(int, {2: 2, 3: 2, 5: 3, 7: 1, 11: 1, 13: 1, 17: 1})

In [1135]:
%%time

a = 2
number = 1
while True:
    divides = 0
    for i in range(1 , int(sqrt(number)+1)):
        if number % i == 0:
            divides += 1
    divides *= 2
    if divides >= 500:
        print(number)
        break
    number += a
    a += 1

76576500
Wall time: 4.58 s


# Problem 13
### 50자리 수 100개를 더한 값의 첫 10자리 구하기
```
아래에 50자리 수가 100개 있습니다. 이것을 모두 더한 값의 첫 10자리는 얼마입니까?
```

In [2]:
s = """
37107287533902102798797998220837590246510135740250
46376937677490009712648124896970078050417018260538
74324986199524741059474233309513058123726617309629
91942213363574161572522430563301811072406154908250
23067588207539346171171980310421047513778063246676
89261670696623633820136378418383684178734361726757
28112879812849979408065481931592621691275889832738
44274228917432520321923589422876796487670272189318
47451445736001306439091167216856844588711603153276
70386486105843025439939619828917593665686757934951
62176457141856560629502157223196586755079324193331
64906352462741904929101432445813822663347944758178
92575867718337217661963751590579239728245598838407
58203565325359399008402633568948830189458628227828
80181199384826282014278194139940567587151170094390
35398664372827112653829987240784473053190104293586
86515506006295864861532075273371959191420517255829
71693888707715466499115593487603532921714970056938
54370070576826684624621495650076471787294438377604
53282654108756828443191190634694037855217779295145
36123272525000296071075082563815656710885258350721
45876576172410976447339110607218265236877223636045
17423706905851860660448207621209813287860733969412
81142660418086830619328460811191061556940512689692
51934325451728388641918047049293215058642563049483
62467221648435076201727918039944693004732956340691
15732444386908125794514089057706229429197107928209
55037687525678773091862540744969844508330393682126
18336384825330154686196124348767681297534375946515
80386287592878490201521685554828717201219257766954
78182833757993103614740356856449095527097864797581
16726320100436897842553539920931837441497806860984
48403098129077791799088218795327364475675590848030
87086987551392711854517078544161852424320693150332
59959406895756536782107074926966537676326235447210
69793950679652694742597709739166693763042633987085
41052684708299085211399427365734116182760315001271
65378607361501080857009149939512557028198746004375
35829035317434717326932123578154982629742552737307
94953759765105305946966067683156574377167401875275
88902802571733229619176668713819931811048770190271
25267680276078003013678680992525463401061632866526
36270218540497705585629946580636237993140746255962
24074486908231174977792365466257246923322810917141
91430288197103288597806669760892938638285025333403
34413065578016127815921815005561868836468420090470
23053081172816430487623791969842487255036638784583
11487696932154902810424020138335124462181441773470
63783299490636259666498587618221225225512486764533
67720186971698544312419572409913959008952310058822
95548255300263520781532296796249481641953868218774
76085327132285723110424803456124867697064507995236
37774242535411291684276865538926205024910326572967
23701913275725675285653248258265463092207058596522
29798860272258331913126375147341994889534765745501
18495701454879288984856827726077713721403798879715
38298203783031473527721580348144513491373226651381
34829543829199918180278916522431027392251122869539
40957953066405232632538044100059654939159879593635
29746152185502371307642255121183693803580388584903
41698116222072977186158236678424689157993532961922
62467957194401269043877107275048102390895523597457
23189706772547915061505504953922979530901129967519
86188088225875314529584099251203829009407770775672
11306739708304724483816533873502340845647058077308
82959174767140363198008187129011875491310547126581
97623331044818386269515456334926366572897563400500
42846280183517070527831839425882145521227251250327
55121603546981200581762165212827652751691296897789
32238195734329339946437501907836945765883352399886
75506164965184775180738168837861091527357929701337
62177842752192623401942399639168044983993173312731
32924185707147349566916674687634660915035914677504
99518671430235219628894890102423325116913619626622
73267460800591547471830798392868535206946944540724
76841822524674417161514036427982273348055556214818
97142617910342598647204516893989422179826088076852
87783646182799346313767754307809363333018982642090
10848802521674670883215120185883543223812876952786
71329612474782464538636993009049310363619763878039
62184073572399794223406235393808339651327408011116
66627891981488087797941876876144230030984490851411
60661826293682836764744779239180335110989069790714
85786944089552990653640447425576083659976645795096
66024396409905389607120198219976047599490197230297
64913982680032973156037120041377903785566085089252
16730939319872750275468906903707539413042652315011
94809377245048795150954100921645863754710598436791
78639167021187492431995700641917969777599028300699
15368713711936614952811305876380278410754449733078
40789923115535562561142322423255033685442488917353
44889911501440648020369068063960672322193204149535
41503128880339536053299340368006977710650566631954
81234880673210146739058568557934581403627822703280
82616570773948327592232845941706525094512325230608
22918802058777319719839450180888072429661980811197
77158542502016545090413245809786882778948721859617
72107838435069186155435662884062257473692284509516
20849603980134001723930671666823555245252804609722
53503534226472524250874054075591789781264330331690
"""

In [14]:
# 정수론 적으로 푸는 건 나중에 생각해보기 :)

str(sum([int(i) for i in s.split('\n')[1:-1]]))[:10]

'5537376230'

# Problem 14
### 백만 이하로 시작하는 우박수 중 가장 긴 과정을 거치는 것은?
```
양의 정수 n에 대하여, 다음과 같은 계산 과정을 반복하기로 합니다.

n → n / 2 (n이 짝수일 때)
n → 3 n + 1 (n이 홀수일 때)

13에 대하여 위의 규칙을 적용해보면 아래처럼 10번의 과정을 통해 1이 됩니다.

13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1
아직 증명은 되지 않았지만, 이런 과정을 거치면 어떤 수로 시작해도 마지막에는 1로 끝나리라 생각됩니다. 
(역주: 이것은 콜라츠 추측 Collatz Conjecture이라고 하며, 이런 수들을 우박수 hailstone sequence라 부르기도 합니다)

그러면, 백만(1,000,000) 이하의 수로 시작했을 때 1까지 도달하는데 가장 긴 과정을 거치는 수는 얼마입니까?

참고: 계산 과정에는 백만을 넘어가는 수가 나와도 괜찮습니다.
```

In [16]:
def CollatzConjecture(n):
    count = 0
    while n != 1:
        if n % 2 == 0:
            n /= 2
        else:
            n = 3 * n + 1
        count += 1
    return count

In [19]:
%%time
hailstone_seq_lengths = [CollatzConjecture(n) for n in range(2, int(1e6)+1)]

Wall time: 22.7 s


In [41]:
np.argmax(hailstone_seq_lengths) + 2

837799

# Problem 15
### 20x20 격자의 최상단에서 우하단으로 가는 경로의 수

In [50]:
def memoize(func):
    buffers = {}
    def wrapped(n):
        buffer = buffers.get(n)
        if buffer is not None:
            return buffer
        return func(n)
    return wrapped


@memoize
def factorial(n):
    if n == 1:
        return 1
    return n * factorial(n-1)

In [57]:
factorial(40) / factorial(20) / factorial(20)

137846528820.0

# Problem 16
### 2^1000의 각 자릿수를 모두 더하면?

In [71]:
sum(int(i) for i in str(2 ** 1000))

1366

# Problem 17
### 1부터 1000까지 영어로 썼을 때 사용된 글자의 개수는?

In [8]:
from num2words import num2words

In [23]:
letters = [num2words(i) for i in range(1, 1001)]
len(''.join(' '.join(letters).split(' ')).replace('-', ''))

21124

# Problem 18
### 삼각형을 따라 내려가면서 합이 최대가 되는 경로 찾기

In [449]:
s = """
75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23
"""

In [450]:
s = s.split('\n')[1:-1]
tree = np.array([
    [int(i) for i in li.split(' ')] + [0] * (len(s)-i) 
    for i, li in enumerate(s, start=1)
])
tree

array([[75,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [95, 64,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [17, 47, 82,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [18, 35, 87, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [20,  4, 82, 47, 65,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [19,  1, 23, 75,  3, 34,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [88,  2, 77, 73,  7, 63, 67,  0,  0,  0,  0,  0,  0,  0,  0],
       [99, 65,  4, 28,  6, 16, 70, 92,  0,  0,  0,  0,  0,  0,  0],
       [41, 41, 26, 56, 83, 40, 80, 70, 33,  0,  0,  0,  0,  0,  0],
       [41, 48, 72, 33, 47, 32, 37, 16, 94, 29,  0,  0,  0,  0,  0],
       [53, 71, 44, 65, 25, 43, 91, 52, 97, 51, 14,  0,  0,  0,  0],
       [70, 11, 33, 28, 77, 73, 17, 78, 39, 68, 17, 57,  0,  0,  0],
       [91, 71, 52, 38, 17, 14, 91, 43, 58, 50, 27, 29, 48,  0,  0],
       [63, 66,  4, 68, 89, 53, 67, 30, 73, 16, 69, 87, 40, 31,  0],
       [ 4, 62, 98, 27, 23,  9, 70

In [401]:
tree.shape

(15, 15)

In [402]:
# 아직 효율적으로 코드를 짜진 못하겠다.
# 그래도 뭐... 일단 문제부터 풀어야지
# 그리고, 웹에서 빠른 속도를 자랑하는 풀이들은 bottom-up
# 그러나 앞으로 내가 풀 문제들 (ex> 강화학습)은 결과를 모름
# 아닌가...? episode 탐색은 전부하니까 아는건가...
# 여튼 뭐 일단 top-down식 검색 방식으로 풀어봄
def TTExplore(tree):
    window = tree.shape[0]
    results = [[0]]
    for i in range(window-1):
        temp = []
        for path in results:
            temp.extend([path+[path[-1]], path+[path[-1]+1]])
        results = temp
    rowind = list(range(1, window))
    maxval, ind = max(
        [(tree[rowind, path[1:]].sum(), path[-1]) for path in results]
    )
    return maxval, ind

In [403]:
%%time
maxval, ind = TTExplore(tree)
print(tree[0, 0] + maxval)

1074
Wall time: 116 ms


# Problem 50
### 1백만 이하의 소수 중 가장 길게 연속되는 소수의 합으로 표현되는 수는?

In [716]:
%%time
primes = [n for n in range(2, int(5e3)) if is_prime(n)]

Wall time: 12 ms


In [717]:
cum_primes = [sum(primes[:i]) for i in range(len(primes))]

In [718]:
%%time
length = 0
ans = None

for lo in range(1, len(cum_primes)):
    for hi in range(lo+length, len(cum_primes)):
        cum_sum = cum_primes[hi] - cum_primes[lo-1]
        if (cum_sum in prime_set) and (hi - lo + 1) > length:
            length = hi - lo + 1
            ans = cum_sum

        if cum_sum > 1e6:
            break
print(ans)

997651
Wall time: 1e+03 µs


# Problem 60
### 다섯 소수 중 어떤 두 개를 이어붙여도 소수가 되는 수 찾기

In [722]:
pre_primes = [3, 7, 109, 673]

In [725]:
%%time
primes = [n for n in range(2, int(5e3)) if is_prime(n)]

Wall time: 12 ms


In [726]:
for prime in pre_primes:
    primes.pop(primes.index(prime))

In [ ]:
for prime in primes:
    for i in pre_prime:
        if (not is_prime(int(str(i)+str(prime))) and
            not is_prime(int(str(prime)+str(i)))):
            break


# Problem 67
### 삼각형에서 경로의 합 중 최댓값을 구하는 효율적인 방법은?

- 아 Bottom-Up으로 짜야하나... 일단 보류

In [432]:
with open('triangle.txt', mode='r') as f:
    tree = f.readlines()
    tree = np.array([
        [int(j) for j in li.split('\n')[0].split(' ')] + [0] * (len(tree)-i)
        for i, li in enumerate(tree, start=1)]
    )

In [477]:
def TTExplore(tree, k=1):
    window = tree.shape[0]
    results = [[0]]
    for i in range(window-1):
        temp = []
        for path in results:
            temp.extend([path+[path[-1]], path+[path[-1]+1]])
        results = temp
    rowind = list(range(1, window))
    results = sorted([(tree[rowind, path[1:]].sum(), path[-1]) for path in results],
           key=lambda x: x[0], reverse=True)[:k]
    output = []
    for result in results:
        if result[1] in [i[1] for i in output]:
            continue
        output.append(result)
    return output

In [481]:
TTExplore(tree, k=1)

1074

In [438]:
def GreedyTTE(tree, num_path):
    j = 0
    MaxVal = tree[0, j]
    for i in range(0, len(tree), num_path):
        semi_tree = tree[i:i+num_path+1, j:j+num_path+1]
        maxval, ind = TTExplore(semi_tree)
        j += ind
        MaxVal += maxval
    return MaxVal, j

In [484]:
tree[0:5, 0:5]

array([[75,  0,  0,  0,  0],
       [95, 64,  0,  0,  0],
       [17, 47, 82,  0,  0],
       [18, 35, 87, 10,  0],
       [20,  4, 82, 47, 65]])

# Problem 93
### 숫자 4개와 사칙연산을 써서 가장 길게 이어지는 숫자 만들기

```
1부터 4까지의 숫자를 한 번씩만 쓰면서, 사칙연산 기호(+, −, *, /)와 괄호를 적절히 조합하면 각기 다른 양의 정수를 여럿 만들어낼 수 있습니다.

몇 가지 예를 들자면 아래와 같습니다.

8 = (4 * (1 + 3)) / 2
14 = 4 * (3 + 1 / 2)
19 = 4 * (2 + 3) − 1
36 = 3 * 4 * (2 + 1)

이 때 12 + 34 처럼 숫자들을 이어붙이지는 않기로 합니다.

이렇게 해서 1 ~ 4의 숫자로는 31개의 다른 결과값(최대 36)을 만들 수 있고, 결과값 중 1부터 28까지는 중간에 끊김 없이 계속 이어집니다.

a < b < c < d 인 숫자 네 개로 위와 같이 했을 때 결과값이 1부터 가장 길게 이어지는 수들을 찾고, abcd 의 형태로 답을 제시하세요.
```

In [940]:
eps = sys.float_info.epsilon


def test(numbers):
    results = []
    for nums in list(permutations(numbers, 4)):
        for ops in list(product(*[['+','-','*','/']]*3)):
            a, b, c, d = nums
            op1, op2, op3 = ops
            v1 = eval(f"(({a}{op1}{b}){op2}{c}){op3}{d}")
            v2 = eval(f"({a}{op1}{b}){op2}({c}{op3}{d})")
            v3 = eval(f"({a}{op1}({b}{op2}{c})){op3}{d}")
            v4 = eval(f"{a}{op1}(({b}{op2}{c}){op3}{d}+{1e-20})")
            v5 = eval(f"{a}{op1}({b}{op2}({c}{op3}{d})+{1e-20})")
            for v in [v1, v2, v3, v4, v5]:
                if round(v) - v < eps * 1e2 and v > 0:
                    results.append(v)                
    return sorted(np.unique(results))


def count_continuous(li):
    c = 1
    is_continuous = True
    while is_continuous:
        c += 1
        if c in li:
            continue
        else:
            is_continuous = False
    return c - 1

In [941]:
%%time
cases = np.unique([sorted(i) for i in cases], axis=0)
results = [count_continuous(test(numbers)) for numbers in cases]

Wall time: 7.88 s


In [942]:
cases[np.argmax(results)]

array([1, 2, 5, 8])